### ISSUE TITLE
Resultados da Unidade 2

### ISSUE THREAD

**Issue by vnsrz** [FGAUnB-REQ-GM/2021.2-DepBot#18]
# Descrição:
Os resultados preliminares devem estar prontos para terça-feira (22/02) para feedback e ajustes.

# Tarefas:

- [x] #22 
- [x] #23
- [x] Quadro kanban 

# Critério de aceitação:

- [x] Backlog de acordo com a estrutura do SAFe
- [x] Backlog em uma seção de anexo
- [x] Quadro kanban disponível para o professor

**Comment by PedroLucasCM** [comment]
Documentos referentes a unidade 2 feitos, só falta gravar o vídeo
