### ISSUE TITLE
Organizar os arquivos do documento em pastas separadas

### ISSUE THREAD

**Issue by PedroLucasCM** [FGAUnB-REQ-GM/2021.2-DepBot#20]
# Descrição:
Precisamos organizar os documentos, principalmente na pasta docs, em pastas separadas para cada arquvo (exceto os do gitpages).

# Tarefas:

- [x] Organizar os arquivos visao.md e canvas.md em pasta separadas.

# Critério de aceitação:

- [x] Organização da pasta docs.

**Comment by victordscabral** [comment]
Pastas organizadas.
