### ISSUE TITLE
Colocar o modelo inicial do Bot no repositorio

### ISSUE THREAD

**Issue by PedroLucasCM** [FGAUnB-REQ-GM/2021.2-DepBot#38]
# Descrição:
Se o modelo inicial do bot estiver funcionando sem erros devemos adicionar ele no repositorio. Coloque em uma pasta " backend " fora da pasta docs.

# Tarefas:

- [x] Criar pasta backend 
- [x] Adicionar modelo inicial do bot na pasta

# Critério de aceitação:

- [x] Pasta backend criada
- [x] Modelo inicial do bot adicionado na pasta

**Comment by Pedro-V8** [comment]
Criei uma branch "develop", para que nosso desenvolvimento antes da R1 seja feita toda por ele, a estrutura inicial já foi adicionada e treinada.
