### ISSUE TITLE
Entrega do MVP 1

### ISSUE THREAD

**Issue by PedroLucasCM** [FGAUnB-REQ-GM/2021.2-DepBot#41]
# Descrição:
Para a Unidade 4 precisamos entregar o MVP1 do produto.
## Observação
A entrega é pro dia 07/04/2022

# Requisitos
- [x] #40 

# Tarefas:

- [x] Produzir o MVP 1

# Critério de aceitação:

- [x] MVP 1 produzido pelo menos 80% de acordo com os documentos entregue em unidades anteriores

**Comment by victordscabral** [comment]
Issue fechada.
