### ISSUE TITLE
Gravar vídeo de apresentação

### ISSUE THREAD

**Issue by PedroLucasCM** [FGAUnB-REQ-GM/2021.2-DepBot#46]
# Descrição:
Precisamos gravar o vídeo de apresentação da unidade 4 para mostrar nosso produto e mudanças em documentações

# Tarefas:

- [x] Gravar vídeo de apresentação

# Critério de aceitação:

- [x] Vídeo upado para a internet
- [x] Link do vídeo no README.md

**Comment by victordscabral** [comment]
Issue fechada.
