### ISSUE TITLE
Revisar Documento de Visão conforme Feedback

### ISSUE THREAD

**Issue by victordscabral** [FGAUnB-REQ-GM/2021.2-DepBot#7]
# Descrição:

Após a apresentação da unidade 1 alguns pontos foram destacados para melhoria. Essa issue tem como objetivo revisar o Documento de Visão com base no feedback feito pelo professor. 

Observação: 
Decidir avaliação dos usuários: Laboratório, questionário e avaliação pelo próprio bot...

# Pré-requisitos:

- [x] #5 
- [x] #1 

# Tarefas (com base no rascunho das anotações):

- [x] "Cujo impacto" E "objetivo do produto". Relacionar ambos. (Visão Geral do Produto - @lbvx)
- [x] Especificar quais os tipos deputados. (Objetivos do Produto - @victordscabral )
- [x] Se apoiar no Sommerville. (Abordagem de Desenvolvimento de Software - @viniciusroriz )
- [x] Casos de uso não vale. Escolher os cenários/stories. (Documentação de Requisitos - @victordscabral )
- [x] Melhorar Verificação de Requisitos (refazer?). Colocar referências. (Verificação de Requisitos - @PedroLucasCM  )
- [x] Gerenciamento de Requisitos. Não ser redundante e escolher uma plataforma. (Gerenciamento de Requisitos - @Pedro-V8)
- [x] Atualizar para a nova versão do Sommerville. Presente na biblioteca virtual da UnB. (Referências Bibliográficas - @lbvx)
- [x] Lições aprendidas: a equipe apresenta uma frase genérica sobre o que aprendeu, não deixando claro qual, de fato, foi o aprendizado. Refazer. (Lições Aprendidas - @lbvx )

# Critério de aceitação:

- [x] Revisão do documento conforme feedback;

**Comment by PedroLucasCM** [comment]
Documento foi revisado, tudo conforme o feedback dado pelo professor.
